// src/hostileSeeds.js
//I went out of my way to make this pre-flight list before moderation is applied pretty exhaustive.
//If cruel language is going unmoderated and you find yourself editing this, you probably should be ejecting people from a server first

module.exports = [
  // strong profanity & direct insults
  "fuck",
  "fuck you",
  "fuck off",
  "fucking idiot",
  "fucking loser",
  "fucking garbage",
  "fucking trash",
  "piece of shit",
  "absolute shit",
  "total shit",
  "shithead",
  "shit for brains",
  "shitbag",
  "asshole",
  "complete asshole",
  "utter asshole",
  "bastard",
  "dumbass",
  "jackass",
  "twat",
  "prick",
  "dickhead",
  "dipshit",
  "scumbag",
  "loser",
  "pathetic loser",
  "idiot",
  "total idiot",
  "complete idiot",
  "moron",
  "imbecile",
  "cretin",
  "numbnuts",
  "worthless",
  "utterly worthless",
  "pathetic",
  "sad excuse",
  "sorry excuse",
  "failure",
  "useless",
  "human garbage",
  "trash",
  "garbage",
  "hot garbage",
  "walking trash",
  "trash person",
  "disgusting",
  "gross",
  "nasty",
  "filthy",
  "vile",
  "revolting",
  "repulsive",
  "degenerate",
  "feral animal",

  // hostility about smell / hygiene
  "you smell",
  "you reek",
  "you stink",
  "you smell like shit",
  "you smell awful",
  "rotten smell",
  "disgusting smell",
  "reeks of garbage",

  // anger / hatred
  "i hate you",
  "hate you",
  "i can't stand you",
  "you make me sick",
  "you disgust me",
  "i despise you",
  "i loathe you",
  "you ruin everything",
  "you're horrible",
  "you're awful",
  "you're terrible",
  "you're the worst",

  // demeaning comparisons
  "you're a worm",
  "you're a rat",
  "you're a mouse",
  "you're a pig",
  "you're a clown",
  "you're a dog",
  "you're a donkey",
  "you're a mule",
  "you're a snake",
  "you're a cockroach",
  "you're a bug",
  "you're an insect",
  "you're a parasite",
  "you're a fungus",
  "you're a slug",
  "you're a leech",

  // degrading language
  "weakling",
  "coward",
  "spineless",
  "brainless",
  "no-brain",
  "empty-headed",
  "pea-brain",
  "airhead",
  "dumb creature",
  "stupid creature",
  "lowest of the low",
  "bottom feeder",
  "subhuman",
  "barely human",

  // harassment / malicious intent
  "kill yourself",
  "kys",
  "go die",
  "drop dead",
  "i hope you die",
  "you should die",
  "you deserve to die",

  // more indirect but hostile
  "nobody likes you",
  "everyone hates you",
  "you ruin everything",
  "you're a burden",
  "you're a plague",
  "you're a menace",
  "you're a joke",
  "you're a failure",
  "worthless mess",
  "walking disaster",
  "waste of air",
  "waste of space",
  "waste of breath",
  "waste of life",
  "total embarrassment",
  "pitiful creature",

  // taunting / mocking
  "cry about it",
  "stay mad",
  "keep crying",
  "cope harder",
  "shut up",
  "shut your mouth",
  "no one asked",
  "nobody cares",
  "go away",
  "buzz off",
  "scram",
  "beat it",
  "get lost",
  "jump off a cliff",

  // additional medium-strength insults
  "clueless",
  "goblin",
  "troglodyte",
  "caveman",
  "gremlin",
  "troll",
  "ogre",
  "orc-brain",
  "idiot child",
  "talking trash pile",
  "walking compost heap",
  "barnyard animal",
  "wet towel",
  "moldy biscuit",
  "stale bread",

  // body-shaming & appearance insults
  "fat",
  "fatass",
  "fat fuck",
  "fat piece of shit",
  "fat garbage",
  "fat pig",
  "you look fat",
  "you're fat",
  "you're too fat",
  "you're disgusting and fat",
  "lose some weight",
  "go lose weight",
  "chubby idiot",
  "big lard ball",
  "lardass",
  "fat lard",
  "you whale",
  "whale",
  "walking whale",
  "you blob",
  "blob creature",
  "ugly",
  "super ugly",
  "disgusting face",
  "ugly face",
  "hideous",
  "hideous creature",
  "you look awful",
  "you look terrible",
  "you look like garbage",
  "gross face",
  "creepy face",
  "weird-looking",
  "you look weird",
  "you look like a clown",
  "deformed-looking",
  "you look malformed",
  "freakish",
  "you freak",
  "you goblin-looking thing",
  "you look like a troll",
  "you look like a rat",
  "ugly goblin",
  "ugly troll",
  "ugly rat",
  "ugly ogre",
  "hunchback",
  "stooped freak",
  "misshapen",
  "you're misshapen",
  "unpleasant to look at",
  "hard to look at",
  "eye sore",
  "walking eyesore",
  "nobody wants to see you",
  "nobody wants to look at you",
  "don't show your face",
  "your face makes me sick",
];

